# Generated by Django 3.0.5 on 2020-05-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
